enum AdminRole {
  owner,
  admin,
  moderator,
  support,
  analyst,
  contentManager,
  aiManager;

  static AdminRole fromString(String role) {
    switch (role.toLowerCase()) {
      case 'owner':
        return AdminRole.owner;
      case 'admin':
        return AdminRole.admin;
      case 'moderator':
        return AdminRole.moderator;
      case 'support':
        return AdminRole.support;
      case 'analyst':
        return AdminRole.analyst;
      case 'content_manager':
      case 'content-manager':
        return AdminRole.contentManager;
      case 'ai_manager':
      case 'ai-manager':
        return AdminRole.aiManager;
      default:
        return AdminRole.analyst;
    }
  }
}

enum Permission {
  viewDashboard,
  viewRevenueDashboard,
  viewAiDashboard,
  viewUsers,
  manageUsers,
  viewUserDetail,
  viewContent,
  manageContent,
  viewTemplates,
  manageTemplates,
  viewEffects,
  manageEffects,
  viewFilters,
  manageFilters,
  viewFonts,
  manageFonts,
  viewAudio,
  manageAudio,
  viewTransitions,
  manageTransitions,
  viewColorGrades,
  manageColorGrades,
  viewAiFactory,
  manageAiFactory,
  generateAi,
  viewAiQueue,
  viewAiReview,
  approveAiReview,
  viewMonetization,
  manageMonetization,
  viewPlans,
  managePlans,
  viewCoupons,
  manageCoupons,
  viewRevenue,
  viewTransactions,
  viewAnalytics,
  viewRetention,
  viewNotifications,
  manageNotifications,
  broadcastNotifications,
  viewSupport,
  manageSupport,
  replySupport,
  viewSettings,
  manageSettings,
  manageAdminUsers,
  manageFeatureFlags,
  viewAuditLogs,
  viewSystemHealth,
  manageSystem,
}

abstract final class RolePermissions {
  static final Map<AdminRole, List<Permission>> permissions = {
    AdminRole.owner: Permission.values,
    AdminRole.admin: [
      Permission.viewDashboard,
      Permission.viewRevenueDashboard,
      Permission.viewAiDashboard,
      Permission.viewUsers,
      Permission.manageUsers,
      Permission.viewUserDetail,
      Permission.viewContent,
      Permission.manageContent,
      Permission.viewTemplates,
      Permission.manageTemplates,
      Permission.viewEffects,
      Permission.manageEffects,
      Permission.viewFilters,
      Permission.manageFilters,
      Permission.viewFonts,
      Permission.manageFonts,
      Permission.viewAudio,
      Permission.manageAudio,
      Permission.viewTransitions,
      Permission.manageTransitions,
      Permission.viewColorGrades,
      Permission.manageColorGrades,
      Permission.viewAiFactory,
      Permission.manageAiFactory,
      Permission.generateAi,
      Permission.viewAiQueue,
      Permission.viewAiReview,
      Permission.approveAiReview,
      Permission.viewMonetization,
      Permission.manageMonetization,
      Permission.viewPlans,
      Permission.managePlans,
      Permission.viewCoupons,
      Permission.manageCoupons,
      Permission.viewRevenue,
      Permission.viewTransactions,
      Permission.viewAnalytics,
      Permission.viewRetention,
      Permission.viewNotifications,
      Permission.manageNotifications,
      Permission.broadcastNotifications,
      Permission.viewSupport,
      Permission.manageSupport,
      Permission.replySupport,
      Permission.viewSettings,
      Permission.manageSettings,
      Permission.viewAuditLogs,
      Permission.viewSystemHealth,
      Permission.manageSystem,
    ],
    AdminRole.moderator: [
      Permission.viewDashboard,
      Permission.viewUsers,
      Permission.manageUsers,
      Permission.viewUserDetail,
      Permission.viewContent,
      Permission.manageContent,
      Permission.viewTemplates,
      Permission.manageTemplates,
      Permission.viewEffects,
      Permission.manageEffects,
      Permission.viewFilters,
      Permission.manageFilters,
      Permission.viewFonts,
      Permission.manageFonts,
      Permission.viewAudio,
      Permission.manageAudio,
      Permission.viewTransitions,
      Permission.manageTransitions,
      Permission.viewColorGrades,
      Permission.manageColorGrades,
      Permission.viewSupport,
      Permission.replySupport,
      Permission.viewNotifications,
    ],
    AdminRole.support: [
      Permission.viewDashboard,
      Permission.viewUsers,
      Permission.viewUserDetail,
      Permission.viewSupport,
      Permission.manageSupport,
      Permission.replySupport,
      Permission.viewNotifications,
    ],
    AdminRole.analyst: [
      Permission.viewDashboard,
      Permission.viewRevenueDashboard,
      Permission.viewAiDashboard,
      Permission.viewAnalytics,
      Permission.viewRetention,
      Permission.viewRevenue,
      Permission.viewUsers,
      Permission.viewUserDetail,
      Permission.viewNotifications,
    ],
    AdminRole.contentManager: [
      Permission.viewDashboard,
      Permission.viewContent,
      Permission.manageContent,
      Permission.viewTemplates,
      Permission.manageTemplates,
      Permission.viewEffects,
      Permission.manageEffects,
      Permission.viewFilters,
      Permission.manageFilters,
      Permission.viewFonts,
      Permission.manageFonts,
      Permission.viewAudio,
      Permission.manageAudio,
      Permission.viewTransitions,
      Permission.manageTransitions,
      Permission.viewColorGrades,
      Permission.manageColorGrades,
      Permission.viewNotifications,
    ],
    AdminRole.aiManager: [
      Permission.viewDashboard,
      Permission.viewAiDashboard,
      Permission.viewAiFactory,
      Permission.manageAiFactory,
      Permission.generateAi,
      Permission.viewAiQueue,
      Permission.viewAiReview,
      Permission.approveAiReview,
      Permission.viewNotifications,
    ],
  };
}
